language: node_js
node_js:
  - "4"
  - "5"
os:
  - linux
sudo: false
before_script:
  - sh -c "git log | head -12"
script: "npm run coverage"
after_script: "npm install coveralls@2.10.6 && cat ./coverage/lcov.info | coveralls"
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate < coverage/lcov.info
